language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

compiler:
  - gcc-4.8

before_install:
  - echo $LANG
  - echo $LC_ALL

script: ./configure && make

os: linux