language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

compiler:
  - g++-4.8

before_install:
  - echo $LANG
  - echo $LC_ALL

script: ./configure CXX=g++-4.8 && make

os: linux
